spring:
  application:
    name: gateway2
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8081/auth/realms/app-realm
        registration:
          keycloak-gateway:
            provider: keycloak-provider
            client-id: gateway
            client-secret: RqxV37NV51Vg9x3JUA4HaD3zrUTWS9gk
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
  cloud:
    gateway:
      routes:
        - id: owner-service
          uri: lb://owner-service
          predicates:
            - Path=/owner/**
          filters:
            - name: CircuitBreaker
              args:
                name: ownerServiceCircuitBreaker
                fallbackUri: forward:/ownerServiceFallback
        - id: dog-service
          uri: lb://dog-service
          predicates:
            - Path=/dog/**
          filters:
            - name: CircuitBreaker
              args:
                name: dogServiceCircuitBreaker
                fallbackUri: forward:/dogServiceFallback
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/reservation/**
          filters:
            - name: CircuitBreaker
              args:
                name: reservationServiceCircuitBreaker
                fallbackUri: forward:/reservationServiceFallback
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
            redis-rate-limiter.requestTokens: 1
  redis:
    connect-timeout: 30s
    host: localhost
    port: 6379
    timeout: 1s

resilience4j:
  circuitbreaker:
    instances:
      ownerServiceCircuitBreaker:
        sliding-window-size: 4
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        automatic-transition-from-open-to-half-open-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info,prometheus
